[tool.poetry]
name = "cad_tickers"
version = "0.1.2"
description = "Various Stock Utilties Created by me"
authors = ["David Li <davidli012345@gmail.com>"]
maintainers = ["David Li <davidli012345@gmail.com>"]
license = "MIT"
readme = "ReadMe.md"
repository = "https://github.com/FriendlyUser/cad_tickers"
documentation = "https://github.com/FriendlyUser/cad_tickers"
keywords = ["Poetry",
            "Stock Tickers",
            "Requests",
            "CSE",
            "TSX"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
coverage = "^5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
